### ISSUE TITLE
no lasagna recipe

### ISSUE THREAD

**Issue by PlaySource** [grillgamesh/MyRecipes#1]
add it >:(((

**Comment by grillgamesh** [comment]
Fair point, I'll have to write one up soon.

**Comment by grillgamesh** [comment]
I asked around my family, and nobody has a lasagna recipe.

I would recommend going to google, and finding a good bolognese, and ricotta recipe, then making lasagna with noodles, and whatever else google says to put in it.

Should I make lasagna myself, that is what I myself, will most certainly will be doing.
